version: '2.1'
services:
  
  statsd-exporter:
    image: prom/statsd-exporter
    command: "--statsd.mapping-config=/tmp/test-mapping.yml \
        --statsd.listen-udp=:8125 \
        --web.listen-address=:9105"
    ports:
      # - "9125:9125"
      - "8125:8125/udp"
    # ports:
    #   - "9123:9105" # port for prometheus pull
    #   - "8125:8125/udp" # port to emit metrics
    volumes:
      - "./test-mapping.yml:/tmp/test-mapping.yml"
  
  prometheus:
    image: prom/prometheus
    command: "--config.file=/tmp/prometheus.yml \
        --log.level=debug \
        --web.listen-address=:9090 \
        --web.page-title='Prometheus - Test Metrics Demo'"
    ports:
      - "9090:9090" # port for health check and grafana
    volumes:
      - "./prometheus.yml:/tmp/prometheus.yml"
